// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDwoPMT1AeemByzRwuXGE2qnPNYmW5Pmg',
    appId: '1:929827470228:web:03a6a7a934d4e19caa2d81',
    messagingSenderId: '929827470228',
    projectId: 'finalpoo-turinajorge',
    authDomain: 'finalpoo-turinajorge.firebaseapp.com',
    storageBucket: 'finalpoo-turinajorge.firebasestorage.app',
    measurementId: 'G-B3M3SP1SKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNsta-aC_ENhyYbvkQ56bxmATq0LGAqTo',
    appId: '1:929827470228:android:1db1e5e564b55242aa2d81',
    messagingSenderId: '929827470228',
    projectId: 'finalpoo-turinajorge',
    storageBucket: 'finalpoo-turinajorge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZ0fr0Pg7AkyKE1lW_rPjsdcvEnVB_zc',
    appId: '1:929827470228:ios:041fad10b941d68baa2d81',
    messagingSenderId: '929827470228',
    projectId: 'finalpoo-turinajorge',
    storageBucket: 'finalpoo-turinajorge.firebasestorage.app',
    androidClientId: '929827470228-9462qkso05t3ppkb5rngvm52854904fq.apps.googleusercontent.com',
    iosClientId: '929827470228-hi9fs8nmfle4htavlse2hbm5f1kree0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalpooTurina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZ0fr0Pg7AkyKE1lW_rPjsdcvEnVB_zc',
    appId: '1:929827470228:ios:041fad10b941d68baa2d81',
    messagingSenderId: '929827470228',
    projectId: 'finalpoo-turinajorge',
    storageBucket: 'finalpoo-turinajorge.firebasestorage.app',
    androidClientId: '929827470228-9462qkso05t3ppkb5rngvm52854904fq.apps.googleusercontent.com',
    iosClientId: '929827470228-hi9fs8nmfle4htavlse2hbm5f1kree0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalpooTurina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8Y5ffX1ZZySV2nC_JxlQpZ8Sn0-6GjWo',
    appId: '1:929827470228:web:d66a37e1a7c098c0aa2d81',
    messagingSenderId: '929827470228',
    projectId: 'finalpoo-turinajorge',
    authDomain: 'finalpoo-turinajorge.firebaseapp.com',
    storageBucket: 'finalpoo-turinajorge.firebasestorage.app',
    measurementId: 'G-CVWLM9MEJ0',
  );
}
